### ISSUE TITLE
using postgres for persistence

### ISSUE THREAD

**Issue by agaldemas** [ging/fiware-idm#1]
I work in a containerized environment (docker)

First to be able to work locally, I modified and moved the Dockerfile in the root repo's directory, to copy the whole repo content instead of getting it from github, then it's possible to modify and rebuild the image without the need to commit on the github repo !

I've configured postgres instead of mysql, in the configuration file

I had to add pg and pg-hstore npm modules in packages.json: 
```
"pg": "~7.4.1",
"pg-hstore": "~2.3.2", 
```
=> this was ok

I modified docker-entrypoint.sh for testing postgres => this is OK
the database is created, but the creation of tables fails (issue with 
`+ ' CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'` 
for string or text type fields) after removing all this in files from migrations directory, 
I managed to get the tables created !
Then issues appeared for population with files from seeders directory: 
the type UUID used for id must respect a particular syntax (https://www.postgresql.org/docs/current/static/datatype-uuid.html) that is checked by postgres, but the content of population files (201802190000-FillUserTable.js) use some simple strings like "admin", which is not a true UUID, then postgres don't accept to insert the data !

I didn't test with mysql, but I suppose that it work with such UUIDs, or because mysql auto-generate UUID from string, but with postgres it causes an issue.

I will try by activating the UUID generator in postgres to see if the problem remains.

But the CHARSET remains an issue.
copy to @Grenouille06

**Comment by aalonsog** [comment]
Hi @agaldemas. Many thanks for the report! Could you make a PR with the fixes? Thanks!

**Comment by agaldemas** [comment]
Hi, I'd like first to try activating the UUID generator in postgres, and see if it works, because for the moment I've changed all UUID typed fields to INTEGER, to create tables and fill the database, so population files are different than for mysql.

to inform @Grenouille06

**Comment by agaldemas** [comment]
Hello,

I managed to fix the seeds files for use with postgres, using true UUID V4, and removing all CHARSET definition at field level in , but there was still a bad issue with the use of database content (role from seeders) in the code, you cannot keep looking on role by the ID "provider" or "purchaser", anywhere in the code and keep the field as an UUID, it's ok with mysql, because very permissive, but with postgres an UUID is checked for the syntax, then you cannot keep UUID type for the role.id.
ti fix this I changed the type to string[32], and added a unique constraint to role.id field.
then I managed to connect, and be able to see the home interface with applications group and organisations group.
I could create an Organization, but it wasn't possible to create an application correctly.
I'm about to issue a PR with my forked repo

**Comment by agaldemas** [comment]
Hello @aalonsog 
If you look at the PR postgres compatibility #26 (https://github.com/ging/fiware-idm/pull/26), you'll see,
I manage to get a fully working container version of Keyrock with postgres,
but loosing mysql compatibility...
I propose some solutions to be able to merge my PR smoothly

**Comment by agaldemas** [comment]
Hello @aalonsog
If you look to my PR #26, you'll see I managed to fix a working version for both mysql and postgres,
Please have a look, and let me know.
I would be great to have your feedback, and subsequently to decide for the merge !
Thanks in advance for your answer

**Comment by agaldemas** [comment]
Hello @aalonsog
Merry Christmas and happy new year
can you have a look at PR #26 and make me a feedback

**Comment by apozohue10** [comment]
Thank you for your PR again @agaldemas! 
You can see en CREDITS file that you figure as contributor.

Regards
