### ISSUE TITLE
Regex for permissions through the API 

### ISSUE THREAD

**Issue by minimalisti** [ging/fiware-idm#100]
@fiware-austria did a great job enabling regex for permission paths in [https://github.com/ging/fiware-idm/pull/88](https://github.com/ging/fiware-idm/pull/88).
But from the files touched in the merge it seems that regex can only be entered for the Web browser. When I was adding permissions through Keyrock's API, I at least couldn't enable the regex.

**Comment by apozohue10** [comment]
Hi @minimalisti. We have fixed this issue in the latest commit. You can check it by downloading the latest version. This bug fixing will be included in the following release of FIWARE.
