### ISSUE TITLE
User wrongly see other users as member of his own organizations

### ISSUE THREAD

**Issue by sirnino** [ging/fiware-idm#103]
I encountered the following strange behavior:

- Login as normal IDM user (let's call him **User_X**)
- Click on an application you are authorized to
- You can see the list of all the users authorized to that application
- Click on one of such users (let's call him **User_Y**)
- In the **User_Y**'s details page, you can see the list of the organizations he belongs to but this list is wrong. It's always the organizations the **User_X** belongs to.

**Comment by apozohue10** [comment]
Hi @sirnino,
You are right, it was wrong. We have fixed this issue in the last commits. Thank you!
Best regards
