### ISSUE TITLE
Broken integration between IdM and PEP

### ISSUE THREAD

**Issue by jmezzera** [ging/fiware-idm#107]
A few days ago, I opened an [issue](https://github.com/ging/fiware-pep-proxy/issues/89) in the PEP repository about a problem in the integration between the two mentioned components. The PEP consumes the IdM API, for user and IoT sensors authentication (same endpoint `IdM/user?`) but expects a user as a response. My guess is that one of the two components grew and diverged from the expected behaviour. 
The problem is detailed in depth in the original issue. 

Any help would be appreciated.

**Comment by apozohue10** [comment]
Hi @jmezzera you are right, the PEP Proxy is currently unable to map IoT attributes to HTTP headers. We will check it as soon as possible!

**Comment by apozohue10** [comment]
Hi again @jmezzera. We have made a new commit fixing this issue. In the upcoming releases it will be available, but you can pull the latest release in which is included the fix.

**Comment by jmezzera** [comment]
Thank you very much @apozohue10. I'll give it a try in the next days and give you some feedback.
