### ISSUE TITLE
npm install not working in OsX 

### ISSUE THREAD

**Issue by joaquindiez** [ging/fiware-idm#11]
this is the error I get

npm install

> mmmagic@0.4.5 install /Users/joaquindiez/repositories/clarity/fiware-idm/fiware-idm/node_modules/mmmagic
> node-gyp rebuild

  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
../deps/libmagic/src/cdf_time.c:101:12: error: variable has incomplete type 'struct tm'
        struct tm tm;
                  ^
../deps/libmagic/src/file.h:619:8: note: forward declaration of 'struct tm'
struct tm *gmtime_r(const time_t *, struct tm *);
       ^
../deps/libmagic/src/cdf_time.c:137:15: warning: implicit declaration of function 'mktime' is invalid in C99 [-Wimplicit-function-declaration]
        ts->tv_sec = mktime(&tm);
                     ^
../deps/libmagic/src/cdf_time.c:171:14: warning: implicit declaration of function 'ctime_r' is invalid in C99 [-Wimplicit-function-declaration]
        char *ptr = ctime_r(sec, buf);
                    ^
../deps/libmagic/src/cdf_time.c:171:8: warning: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
        char *ptr = ctime_r(sec, buf);
              ^     ~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.
make: *** [Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/joaquindiez/repositories/clarity/fiware-idm/fiware-idm/node_modules/mmmagic
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.4.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.4.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joaquindiez/.npm/_logs/2018-05-05T08_20_00_575Z-debug.log
J10:fiware-idm joaquindiez$

**Comment by apozohue10** [comment]
Hi @joaquindiez,
Have you tried to update node and npm version? For instance, with Ubuntu 16.04, node version 9.8 and npm version 5.6 it works.

**Comment by joaquindiez** [comment]
I know in ubuntu works, but not in OSX, I reinstalled everything, but the problem is with one dependency, mmmagic, that need to be compiled with c libraries??? Why do you use this?

**Comment by apozohue10** [comment]
We use it to detect MIME type when uploading  an image through the web portal. We have recently removed these dependency in several files and now is only used in lib/image.js, which is called from organization, user and application controllers.
I recommend you to use the docker image which usually has no problems with dependencies or differents operating systems.
