### ISSUE TITLE
Cannot authenticate Iot Sensors using Fiware IDM and PEP proxy

### ISSUE THREAD

**Issue by raiuli** [ging/fiware-idm#113]
Hi,

I am using Fiware IDM 7.0.0 and PEP proxy 7.0.2. I am using following command to get the token for IOT sensor 
`curl -X POST \
  http://130.240.xxx.xxx:3000/oauth2/token \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic MGY4OWYzNjktMGFmYi00NmM3LTk0YjItNmY4ZGQ0ODE0ZDVhOjQ4MGIzNDRjLWM4ZjktNDcyNi04YTdkLTI4N2QyOTE2MjM4Ng==' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 133' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Cookie: session=eyJyZWRpciI6Ii8ifQ==; session.sig=TqcHvLKCvDVxuMk5xVfrKEP-GSQ' \
  -H 'Host: 130.240.134.132:3000' \
  -H 'Postman-Token: a19c0385-0ddd-4078-8afb-ac5399017f20,88e2d6cf-da92-40bc-9f63-3ebecf7d1a6d' \
  -H 'User-Agent: PostmanRuntime/7.16.3' \
  -H 'cache-control: no-cache' \
  -d 'grant_type=password&username=iot_sensor_d9bfbb88-6fc2-4cae-87f6-173f8e2e49d3&password=iot_sensor_95c6d7a8-2416-405e-9f24-91f132b2be83'`

Afterwards, i am getting trying to send request for data to pep proxy with that token for that I am sending the following message 
`curl -X POST \
  http://130.240.xxx.xxx:8050/v1/updateContext \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 6' \
  -H 'Content-Type: text/plain' \
  -H 'Cookie: session=eyJyZWRpciI6Ii8ifQ==; session.sig=TqcHvLKCvDVxuMk5xVfrKEP-GSQ' \
  -H 'Host: 130.240.xxx.xxx:8050' \
  -H 'Postman-Token: 240feb22-18ac-4a36-8411-11680627fb2b,fe00ed53-3cb4-410d-89e7-172af67365c1' \
  -H 'User-Agent: PostmanRuntime/7.16.3' \
  -H 'X-Auth-Token: 65bea3d480700aa9d0525210a342a6c288b48a91' \
  -H 'cache-control: no-cache' \
  -d '{test}'`

The response is following 

{
    "statusCode": 401,
    "status": 401,
    "code": 401,
    "message": {
        "error": "invalid_token"
    },
    "name": "invalid_token"
}

Following is the log from PEP proxy
sudo: unable to resolve host fiwareaaa2
2019-09-11 11:50:49.424  - INFO: Server - Starting PEP proxy in port 8050. IdM authentication ...
2019-09-11 11:50:49.617  - INFO: Server - Success authenticating PEP proxy. Proxy Auth-token:  7c8460e4-cae2-4731-be2d-ed500accbdc1
2019-09-11 11:50:49.618  - INFO: Server - Success authenticating PEP proxy.
2019-09-11 11:51:13.366  - INFO: IDM-Client - Checking token with IDM...
2019-09-11 11:51:13.389  - ERROR: IDM-Client - Error in IDM communication  {"statusCode":401,"status":401,"code":401,"message":{"error":"invalid_token"},"name":"invalid_token"}
2019-09-11 11:51:13.389  - ERROR: Root - { statusCode: 401,
  status: 401,
  code: 401,
  message: { error: 'invalid_token' },
  name: 'invalid_token' }
and following is the out put from Fiware idm

[sass]  skip: /user nothing to do
Executing (default): SELECT `OauthAccessToken`.`access_token`, `OauthAccessToken`.`access_token` AS `accessToken`, `OauthAccessToken`.`expires` AS `accessTokenExpiresAt`, `OauthAccessToken`.`scope`, `User`.`id` AS `User.id`, `User`.`username` AS `User.username`, `User`.`email` AS `User.email`, `Iot`.`id` AS `Iot.id`, `OauthClient`.`id` AS `OauthClient.id`, `OauthClient`.`grant_type` AS `OauthClient.grant_type` FROM `oauth_access_token` AS `OauthAccessToken` LEFT OUTER JOIN `user` AS `User` ON `OauthAccessToken`.`user_id` = `User`.`id` LEFT OUTER JOIN `iot` AS `Iot` ON `OauthAccessToken`.`iot_id` = `Iot`.`id` LEFT OUTER JOIN `oauth_client` AS `OauthClient` ON `OauthAccessToken`.`oauth_client_id` = `OauthClient`.`id` WHERE `OauthAccessToken`.`access_token` = '65bea3d480700aa9d0525210a342a6c288b48a91';
GET /user?access_token=65bea3d480700aa9d0525210a342a6c288b48a91 401 30.026 ms - 101
Any one can tell me what might be the problem

**Comment by tmontanaro** [comment]
Did you try to restart the IdM?

**Comment by raiuli** [comment]
Yup i did. I am not sure if there is any problem with date and time. I am using UCT+2 when sending request but Fiware-IDM is using UCT time.

**Comment by tmontanaro** [comment]
While, when did you generate the token?
It seems you are using an old token!?

**Comment by raiuli** [comment]
i send the request few minutes apart

**Comment by tmontanaro** [comment]
Ok, let's analyze what should be done to let them work.
a) open the IdM interface in a browser at http://130.240.xxx.xxx:3000
b) create an application
c) create a Role
d) create a Permission to access you URL (e.g., PATH: v1/updateContext and METHOD: GET)
e) associate the Permission to the created Role
f) associate the Role to the user
g) Open Postman and request a new token (POST request to http://130.240.xxx.xxx:3000/oauth2/token with attached "Authorization" and "Content-Type" in header and "username", "password" and "grant_type" in body
h) try to make your request by passing the obtained token in header ("X-auth-token" property)

Did you do everything?

**Comment by raiuli** [comment]
I asssigned the default role and permissions. i did not create any separate roles or permissions.

**Comment by tmontanaro** [comment]
Actually the role could remain the one that is present by default (and I hope it is already associated to the user), but the permissions should be inserted as needed. Thus if you want to access a resource that is available at path /v1/updateContext you should create a permission with that path and the GET method.

Consider also that /v1/updateContext is different from /v1/updateContext/ (with an additional slash at the end) that is also different from /v1/updateContext/trial (with an additional word at the end) so you should create a permission for each possible path you want to enable.
If you want to create more complicated permissions you can use the XACML code, but I will the word to FIWARE staff to introduce it if necessary ;-)

**Comment by raiuli** [comment]
I was checking the communiction between pep proxy and fiware-idm. the communication is following. There are no passing of the path.
GET /user?access_token=c54130c6e19b1607d008ad4aa8900dc7b67ef883 HTTP/1.1
User-Agent: node-XMLHttpRequest
Accept: */*, application/json
X-Auth-Token: 92ccfac0-c7a4-4fa5-802a-5f0f19985113
Host: 130.240.xxx.xxx:3000
Connection: close

HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Content-Type: application/json; charset=utf-8
Content-Length: 101
ETag: W/"65-i6pknlumlQcbRK+xOkxOkpdYTmU"
Set-Cookie: session=eyJyZWRpciI6Ii8ifQ==; path=/; expires=Wed, 11 Sep 2019 15:28:21 GMT; httponly
Set-Cookie: session.sig=TqcHvLKCvDVxuMk5xVfrKEP-GSQ; path=/; expires=Wed, 11 Sep 2019 15:28:21 GMT; httponly
Date: Wed, 11 Sep 2019 11:28:21 GMT
Connection: close

{"statusCode":401,"status":401,"code":401,"message":{"error":"invalid_token"},"name":"invalid_token"}
