### ISSUE TITLE
Multiple bugs with idm-knowage integration

### ISSUE THREAD

**Issue by sergiorb** [ging/fiware-idm#114]
Hi, 

I'm following the steps described in the official [guide](https://knowage.readthedocs.io/en/latest/admin/README/index.html#configuration-with-the-idm-keyrock) to integrate IDM with Knowage through Oauth2.
I've found two issues in this process that makes impossible to achieve the integration:

1. In the authorization request (authorization page) you have to manually add the param "state=someRandomString" in order to fulfill it. This is due to this [line](https://github.com/oauthjs/node-oauth2-server/blob/90d00495842cbc68869214a4e6696e5ad048c93d/lib/handlers/authorize-handler.js#L220) in the [Oatuh2-server](https://github.com/oauthjs/node-oauth2-server):
`if (!this.allowEmptyState && !state) {`
I've searched how to set `this.allowEmptyState` but I've not found anything.

2. When knowage calls IDM to retrieve user's details from `GET /user?access_token=2b984...` the endpoint respond with a **201 status code**. This comes into conflict with the following [line](https://github.com/KnowageLabs/Knowage-Server/blob/f1b091dcc0c25f69e67ee40047d8100ca8b434be/knowageoauth2securityprovider/src/main/java/it/eng/spagobi/security/OAuth2SecurityServiceSupplier.java#L51) in Knowage:
`if (statusCode != HttpStatus.SC_OK) { // 201`
I have to manually enter in the container and change that line to return 200 status code if I want to overcome this point.
I don't know why it returns that code but from my understanding that endpoint should return a 200 code because, as far as I know, it's not creating anything. May I send a PR with this change?

Thanks in advance.

**Comment by apozohue10** [comment]
Hi @sergiorb,

startin with the second case, you are right, it should be 200 code. We have changed it in the last commit

For the first issue, you have made me think that it could be useful to include that parameter in the config file of Keyrock, so we have made a commit including this parameter in the configuration file. To include these changes you should follow the following steps:

1.  Git pull last changes from master branch
2.  Go to config.js.template file and copy the following line from oauth configuration into you config.js file:
`allow_empty_state: (process.env.IDM_OAUTH_EMPTY_STATE || false)`
3. Set this value to true and this should make the trick

Regards

**Comment by JoseSecmotic** [comment]
Hi @apozohue10 !

As I see, the CI has failed since the tests have not been modified. Are the changes reflected in the docker image of IdM if the tests do not pass?

Thanks in advance

**Comment by sergiorb** [comment]
@apozohue10 Wonderful! 

I'll try what you said while these changes reach the docker registry. 

Thanks!

**Comment by apozohue10** [comment]
Hi @JoseSecmotic and @sergiorb , we usually have the latest docker image updated at the same time as the master branch in github repository, so tests should be passed for both. Tests fail this week because we were including the oauth allow empty state functionality. But, the CI build is OK now and the docker image is up to date.

**Comment by sergiorb** [comment]
Hi @apozohue10, it seems that everything is ok now. I'm closing this issue. Thank you!
