### ISSUE TITLE
Knowage+idm - public cockpit authentication error

### ISSUE THREAD

**Issue by sergiorb** [ging/fiware-idm#115]
Hi,

After connecting Knowage with Idm, I've created a cockpit to be visualized by unauthenticated users. I've added a role with "is public role" enabled and code "PUBLIC" in order to create the link/embed code (http://host:port/knowage/public/servlet/AdapterHTTP?ACTION_NAME=EXECUTE_DOCUMENT_ACTION&OBJECT_LABEL=a_scope_user&TOOLBAR_VISIBLE=true&ORGANIZATION=DEFAULT_TENANT&NEW_SESSION=true).

When I access the link through the browser, the content cant be visualized due to the following error:
`GET /user?access_token=eyJ0eXAiOiJK.... 401`

That JWT contains the following payload:
```
{
  "user_id": "public-DEFAULT_TENANT",
  "exp": 1569278214
}
```

I've created a user in IDM and manually changed its id with a sql update to match the previous one but fails anyways.

After some debugging (btw, it seems that `- IDM_DEBUG=true` doesn't work) i've found that the problem could be with this [line](https://github.com/ging/fiware-idm/blob/e9d4b88d7cd193ca9f4979fa1af678ac7dd78eee/controllers/oauth2/oauth2.js#L344).

- Could anybody give me some hits at this?
- Is it necessary to create that `public-DEFAULT_TENANT` user or am I miss-configuring something?

Thanks you in advance

**Comment by apozohue10** [comment]
Hi @sergiorb,
First of all, the IDM_DEBUG option enables to check logs only of SQL requests. If you need more information you can run Keyrock with `npm run debug` or with `DEBUG=idm:*,oauth2-server:*  npm start` in case you don't have nodemon installed.

Secondly, if you send a request to Keyrock to check a JWT, you need to include a query string with the application id. For instance:

/user?access_token=eyJ0eXAiOiJK....&app_id=04f....

In such a way, Keyrock is abled to verify the JWT.

**Comment by sergiorb** [comment]
Hi @apozohue10,

Got it. Anyway, It would be nice to have the option to activate `npm run debug` with some sort of env like `IDM_DEBUG`. :smile: 

So Its seems to be a problem with knowage implementation then. I'll try to resolve the issue in their repo.

Thank you!
