### ISSUE TITLE
Manage CORS

### ISSUE THREAD

**Issue by RaulSantosCalvo** [ging/fiware-idm#116]
Hi all,

I'm trying to access the IdM container API from a web application. I am unable to access no matter how I configure the container environment variables, due to preflight requests rejection.

I have tried to disable CORS, enable my address (even localhost), and so on.

I have read in another topic regarding this issue that CORS was not able to be managed and only accepts 4 methods https://github.com/ging/fiware-idm/issues/25 from a year ago. Is this still like this? No change scheduled?

I have my backend protected by pep-proxy + IdM, so if I rather not access the IdM from a redirection or operation from the backend.

Thank you in advance.
Best regards

**Comment by apozohue10** [comment]
Hi @RaulSantosCalvo,

How are you enabling the CORS using the environment variables? If the problem is the rejection of the preflight request, CORS should be enabled in the IdM configuration.

Anyways, why do you need to send requests to the API of IdM from a web page?

best regards
