### ISSUE TITLE
Organization Create API allows Create Organizations with same name

### ISSUE THREAD

**Issue by joaquindiez** [ging/fiware-idm#13]
Don't you think you should not allow creating organizations, with the same name?

the name is also a Unique Key in the system, and Having several Organizations with the same name could provoke confusion

**Comment by RiosQ** [comment]
Origanizations, Apps, and other things...  the API applied on IDM generate an unique id, in other words, to have many organizations or apps with the same name is not a issue because the primary key is always different and isn't the name of the element

**Comment by apozohue10** [comment]
Yes there as @RiosQ said there is an unique id to identify each element but you are right it could provoke some confusion. We would try to solve it as soon as posible.

**Comment by aalonsog** [comment]
By the moment, the unique id is not the entity name but the database id.
