### ISSUE TITLE
Error in Validation Content-Type Header

### ISSUE THREAD

**Issue by joaquindiez** [ging/fiware-idm#14]
in check_create_token_request your are making and strict validation header content-type to be equals 

to application/json, but this is not correct as the http Standard allows to send this header as follows

Content-Type:application/json; charset=utf-8

so you validation is generating an error 
Missing parameter: header Content-Type: application/json'

when the header is correctly sended

**Comment by apozohue10** [comment]
I see your pull requests and I merged it with your solution. Thank you. I will close this issue.
