### ISSUE TITLE
API changes after OpenID connect extention?

### ISSUE THREAD

**Issue by ktsakos** [ging/fiware-idm#149]
Are there any changes on the API usage of Keyrock after the openid connect implementation merging?

Are you going to update your documentation?

Which changes are we going to notice?

**Comment by apozohue10** [comment]
Hi @ktsakos,

the openID Connect implementation is built on the top of OAuth 2.0 protocol, so the API usage is the same as before but including the OIDC functionalities. We will update the documentation ASAP.  OIDC can be easily activated via Keyrock's web interface if you want to test it. You can find the common OIDC flows on its [documentation](https://openid.net/specs/openid-connect-core-1_0.html)

regards
