### ISSUE TITLE
3rd party application logins

### ISSUE THREAD

**Issue by ilarimikkonen** [ging/fiware-idm#163]
In a scenario where there are multiple Keyrock Applications (Applications created in Keyrock) I had assumed that Keyrock users are only allowed to login to a 3rd party application where the corresponding `Client id` is configured. How ever this does not seem to be the case. Here is a scenario:

1) Create an application in keyrock (give all grants).
2) Configure that to a 3rd party application login (say API Management).
3) Create a user in Keyrock.
4) With this user created in step 3, using UI, login to 3rd party application.

Assumed: user is not allowed to login, as user is not Authorized in the application
Actual: User can login

Can you please give guidelines on how 3rd party applications are supposed to implement the logins and what principles to use in User management. Can Keyrock (or IDMs in general) be used for the scenario I outlined above? What grants should be used? How is the application to be configured?

**Comment by aalonsog** [comment]
Dear @ilarimikkonen, FIWARE security ecosystem supports three levels of authorization. By default, applications use Level 1 that means every user registered in Keyrock is able to login in the registered application. For managing access you should use Level 2, defining and assigning roles and permissions to the users. 

You can check [Keyrock](https://fiware-idm.readthedocs.io/) and [Wilma](https://fiware-pep-proxy.readthedocs.io/) documentation to check how this can be implemented. You can also check [FIWARE tutorials](https://github.com/FIWARE/tutorials.Step-by-Step#security-identity-management) where examples are provided.
