### ISSUE TITLE
Reporting of Security Issues

### ISSUE THREAD

**Issue by FlorianCodes** [ging/fiware-idm#169]
Hi developers,

I found some vulnerabilities and security bad practices in Keyrock.

This project does not seem to have any security contact. Despite from public GitHub issues, **where or to whom can I report these findings?**

CC @apozohue10 @jason-fox since many commits came from you.

**Comment by jason-fox** [comment]
Hi Florian, I am just a contributor to this repository. For something more sensitive you will need to contact @aalonsog or @apozohue10 - Git. If you reach out to me on [LinkedIn](https://www.linkedin.com/in/jason-fox-8a79563/) I can pass on the necessary contact details.

**Comment by FlorianCodes** [comment]
Thank you for sharing the contact details, @jason-fox. I will close this issue.
