### ISSUE TITLE
how to allow only admin users to register new organizations and applications?

### ISSUE THREAD

**Issue by carlosapgomes** [ging/fiware-idm#17]
Is there a way to configure fiware-idm to allow only admin users to register new organizations and new applications?
I am trying to use fiware-idm as an id manager for an organization that has 5-6k employees, a dozen departments and several applications, and, as I understood from the docs, any user can register new organizations and apps. I am afraid that it can have some security implications. 
Or should I create my own idm front-end and manage those cases using the REST API?
Thanks,

Carlos

**Comment by apozohue10** [comment]
Hi @carlosapgomes 

By the moment there is no way to configure fiware-idm with this functionality but we want to add in the next release.

**Comment by carlosapgomes** [comment]
Hi @apozohue10 
thanks for your comment.
I ended up posting a PR about [this functionality](https://github.com/ging/fiware-idm/pull/19).
It kind of worked for me. But I did not test it enough.

**Comment by apozohue10** [comment]
Hi @carlosapgomes 

Thank you for your pull request. We will check it and extend admin functionality.
