### ISSUE TITLE
Internal error (Code: 500)

### ISSUE THREAD

**Issue by flopezag** [ging/fiware-idm#192]
# Description

I get an internet error every time that I try to get details about the user clicking in the username, both in Organisations, Users, and Authorised users in applications. Nevertheless, if I try to show this information for the current registered user, Alice the Authorised Administrators there is no problem.

# Environment

Keyrock docker image latests (fiware/idm:latest
DIGEST:sha256:93464c7353e2915cebeaf767f470cdca9b3dc0c47baea13a7cc0f2a8c477a515)

# Reproduction

- Create a specific user:

    echo '{
        "user": {
        "username": "Bob",
        "email": "bob-the-appmanager@test.com",
        "password": "test"
        }
    }' | http  POST 'http://localhost:3005/v1/users' X-Auth-Token:"$TOKEN"

- Access to IdM with the Alice (authorised administrator)
-  Click on users (for the simple case)
- Clink on Username "Bob" in the table

Result:

![image](https://user-images.githubusercontent.com/1379796/112163507-63a1f300-8bed-11eb-8e6c-82af575f9b18.png)

**Comment by jason-fox** [comment]
It looks like the `extra` field cannot be left as `null`, but should default to an empty object `{}` instead.


Amending the tutorial test users as shown displays the page correctly:

```diff
 LOCK TABLES `user` WRITE;
 /*!40000 ALTER TABLE `user` DISABLE KEYS */;
 INSERT INTO `user` VALUES 
+('aaaaaaaa-good-0000-0000-000000000000','alice', 'Alice is the admin',NULL,'default',0,'alice-the-admin@test.com','89e48c55e4e4b3b86141fb15f5e6abf70f8c32c0', 'fbba54b6750b16e8', '2018-07-30 11:41:14',1,1,'{\"visible_attributes\": [\"username\", \"description\"]}',NULL,0,NULL),
-('aaaaaaaa-good-0000-0000-000000000000','alice', 'Alice is the admin',NULL,'default',0,'alice-the-admin@test.com','89e48c55e4e4b3b86141fb15f5e6abf70f8c32c0', 'fbba54b6750b16e8', '2018-07-30 11:41:14',1,1,NULL,NULL,0,NULL),
+('bbbbbbbb-good-0000-0000-000000000000','bob','Bob is the regional manager',NULL,'default',0,'bob-the-manager@test.com','89e48c55e4e4b3b86141fb15f5e6abf70f8c32c0', 'fbba54b6750b16e8', '2018-07-30 11:41:14',1,0,'{\"visible_attributes\": [\"username\", \"description\"]}',NULL,0,NULL),
-('bbbbbbbb-good-0000-0000-000000000000','bob','Bob is the regional manager',NULL,'default',0,'bob-the-manager@test.com','89e48c55e4e4b3b86141fb15f5e6abf70f8c32c0', 'fbba54b6750b16e8', '2018-07-30 11:41:14',1,0,NULL,NULL,0,NULL),
+('cccccccc-good-0000-0000-000000000000','charlie','Charlie is head of security',NULL,'default',0,'charlie-security@test.com','89e48c55e4e4b3b86141fb15f5e6abf70f8c32c0', 'fbba54b6750b16e8', '2018-07-30 11:41:14',1,0,'{\"visible_attributes\": [\"username\", \"description\"]}',NULL,0,NULL),
-('cccccccc-good-0000-0000-000000000000','charlie','Charlie is head of security',NULL,'default',0,'charlie-security@test.com','89e48c55e4e4b3b86141fb15f5e6abf70f8c32c0', 'fbba54b6750b16e8', '2018-07-30 11:41:14',1,0,NULL,NULL,0,NULL),

/*!40000 ALTER TABLE `user` ENABLE KEYS */;
 UNLOCK TABLES;
```
