### ISSUE TITLE
DOCKER: When querying version through the API, the same value is obtained. | curl get localhost:3005/version 

### ISSUE THREAD

**Issue by MRROOX** [ging/fiware-idm#196]
Hi all, I have been doing a couple of tests to determine the version of keyrock that is running a long time ago on a production server, for this I have used the api. I have made the following query :

curl fw-idm.prodserver.com/version 

and the answer is the following:
`{"keyrock":{"version":"7.0.1","release_date":"2018-06-25","uptime":"18:50:36.1","git_hash":"https://github.com/ging/fiware-idm/releases/tag/7.0.1","doc":"https://fiware-idm.readthedocs.io/en/7.0.1/","api":{"version":"v1","link":"http://10.10.10.100:3005/v1"}}}`
 
In the response you can see that the keyrock version is :

`"version":"7.0.1"`

Locally I have done some tests to know the keyrock version with different keyrock versions (latest, 7.9.2, 7.6.0). And I get the same answer from the keyrock that is on the production server.

fiware/idm:lastet

`{"keyrock":{"version":"7.0.1","release_date":"2018-06-25","uptime":"00:00:20.9","git_hash":"https://github.com/ging/fiware-idm/releases/tag/7.0.1","doc":"https://fiware-idm.readthedocs.io/en/7.0.1/","api":{"version":"v1","link":"http://localhost:3000/v1"}}}`

fiware/idm:7.9.2

`{"keyrock":{"version":"7.0.1","release_date":"2018-06-25","uptime":"00:00:07.6","git_hash":"https://github.com/ging/fiware-idm/releases/tag/7.0.1","doc":"https://fiware-idm.readthedocs.io/en/7.0.1/","api":{"version":"v1","link":"http://localhost:3000/v1"}}}`

fiware/idm:7.6.0

`{"keyrock":{"version":"7.0.1","release_date":"2018-06-25","uptime":"00:38:20.9","git_hash":"https://github.com/ging/fiware-idm/releases/tag/7.0.1","doc":"https://fiware-idm.readthedocs.io/en/7.0.1/","api":{"version":"v1","link":"http://localhost:3000/v1"}}}`

I used a docker-compose.yml file, I just changed the version of fiware/idm:<version>.

I think that in the docker versions of keyrock the information obtained through the API has not been updated.

Regards!

**Comment by jason-fox** [comment]
> I think that in the docker versions of keyrock the information obtained through the API has not been updated.

I agree with this analysis. The values for `/version` need to be generated from a maintained location.
