### ISSUE TITLE
v7 API functions unreachable 404 token not found

### ISSUE THREAD

**Issue by caballero03** [ging/fiware-idm#20]
I have been working on discovering what I can get from the API in Keyrock. I have not had much luck.

It would appear that the API is using the wrong table to look up access tokens. The queries in the logfile show the use of the auth_token table for the token owner. It does seem that the actual access token data is, instead being stored in the oauth_access_token table.

Here is the query I am getting (in the log) for *any* v1 or v3 API endpoint (truncated for brevity):
Executing (default): SELECT `AuthToken`.`access_token`, `AuthToken`.`expires`, `AuthToken`.`valid`, `AuthToken`.`user_id`, `AuthToken`......
FROM `auth_token` AS `AuthToken` <<<------ should be oauth_access_token table?
LEFT OUT..... WHERE `AuthToken`.`access_token` = '5478.....ade';
GET /v1/users 404 3.952 ms - 70

I traced the relevant call to here:
https://github.com/ging/fiware-idm/blob/c696dfc0ad021f4d3d1039c11e27a4a8dfa43d00/controllers/api/authenticate.js#L350

I don't have a full development environment set up for this yet so I am unable to try to fix this on my own. I am currently running the IdM with a docker image.

Any ideas? Am I right that this is not the desired behaviour?

**Comment by emepetres** [comment]
Could this be related to #18?

**Comment by caballero03** [comment]
I don't think the two problems are closely related, no. 

I do think there is some unfinished transitions from the older IdM code base. Perhaps just an oversight.

**Comment by apozohue10** [comment]
Hi @caballero03 

There are two types of token in the IDM: to manage the API and OAuth2 Tokens. Perhaps you are creating an OAuth2 token to perform requests to the API.

You can see how to create a token to manage the API in this [link](https://keyrock.docs.apiary.io/#reference/keyrock-api/authentication/create-token-with-password-method)

**Comment by ah223vp** [comment]
@apozohue10 But does that mean that we can not use the same token for the oauth and api? If I then use oauth to log the user in I still need to promt the user to get the username and password to do api actions?

**Comment by apozohue10** [comment]
Hi @ah223vp,

You use oauth2 tokens when you want to provide your application with authentication and authorization mechanism in a delegated way and an API token when you need to create resources directly on the IDM.

In your case, if your users need to make a request to the IDM, they do not need OAuth authentication but they only have to create an API token using their username and password.

**Comment by caballero03** [comment]
Thank you for that! That was what I mas missing. Now I have some work to do. :-D
