### ISSUE TITLE
Configure Mysql port

### ISSUE THREAD

**Issue by RiosQ** [ging/fiware-idm#21]
i'm trying to change teh mysql port for the Database, but can't find them in a config file, do you know how  to change the 3306 port to the 3366?

**Comment by apozohue10** [comment]
Hi @RiosQ 
I think you need to make two changes. In config.js file add port line to database configuration as this:

`// Database info`
`config.database = {`
`    host: database_host, ` 
`    password: 'idm',       `
`    username: 'root',       `    
`    database: 'idm',          `
`    dialect: 'mysql',           `
`    port: 3366              `
`};`

You also need to specify port when creating a sequelize instance in models/models.js:

`var sequelize = new Sequelize(database.database, database.username, database.password, { `
`    host: database.host,`
`    dialect: database.dialect,`
`    port: 3366`
`});`

This should do the trick.
