### ISSUE TITLE
Manage OPTIONS request to the KeyRock API

### ISSUE THREAD

**Issue by olivertem** [ging/fiware-idm#25]
I´m trying to access the KeyrRock Api like in the url : https://keyrock.docs.apiary.io/#reference/keyrock-api/authentication/create-token-with-password-method. 

For example to create a token with user and password, **POST https://keyrock/v1/auth/tokens**

The problem is than when a try to do a request post in a web browser to the API the browser automatically do an OPTIONS requets first, and the KeyRock can manage the OPTIONS requests because only allows POST,GET,HEAD,DELETE method.

How can I configure the fiware-idm proyect to solve this?
(I think that the problem can be for the CORS configuration)

**Comment by aalonsog** [comment]
Right now CORS is not enabled for Keyrock API. So you have to manage the API from a backend. This is not an issue but a new feature. We will add in in the roadmap and of course if you want to implement and contribute the feature it would be perfect :)
