### ISSUE TITLE
Getting Started Guide example not working

### ISSUE THREAD

**Issue by ChristophBaierATB** [ging/fiware-idm#257]
Expected behavior:
Following the instruction in the [Getting Started Guide](https://fiware-idm.readthedocs.io/en/latest/getting_started/index.html), I set up the idM via the docker-compose.yml mentioned there. After executing the first curl command, I expected a successful transaction and a 'X-Subject-Token' return value.

Actual behavior:
The execution of `docker-compose up` showed a database creation error in the
[logs](https://github.com/ging/fiware-idm/files/7632216/logs.txt). The [curl output](https://github.com/ging/fiware-idm/files/7632228/curl-output.txt) seems to be a follow-up issue which does not provide the expected 'X-Subject-Token' due to an unauthorized access attempt.

**Comment by gr-hovest-atb** [comment]
Same problem here: 

I followed the getting started guide at https://fiware-idm.readthedocs.io/en/latest/getting_started/index.html today and I observed the exact same issues. 

After creating a `docker-compose.yml` and running `docker-compose up`, the following error is displayed:

```
fiware-keyrock-mysql-1       | [Entrypoint] Starting MySQL 5.7.21-1.1.3
fiware-keyrock-fiware-idm-1  | Unable to create database:  Error: Command failed: npm run create_db --silent
fiware-keyrock-fiware-idm-1  | Thu, 20 Jan 2022 11:24:16 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:245:13
fiware-keyrock-fiware-idm-1  | ERROR: Access denied for user 'idm'@'172.18.1.6' (using password: YES)
fiware-keyrock-fiware-idm-1  | 
fiware-keyrock-fiware-idm-1  |     at ChildProcess.exithandler (child_process.js:308:12)
fiware-keyrock-fiware-idm-1  |     at ChildProcess.emit (events.js:314:20)
fiware-keyrock-fiware-idm-1  |     at maybeClose (internal/child_process.js:1022:16)
fiware-keyrock-fiware-idm-1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
fiware-keyrock-fiware-idm-1  |   killed: false,
fiware-keyrock-fiware-idm-1  |   code: 1,
fiware-keyrock-fiware-idm-1  |   signal: null,
fiware-keyrock-fiware-idm-1  |   cmd: 'npm run create_db --silent'
fiware-keyrock-fiware-idm-1  | }
```

**Comment by ChristophBaierATB** [comment]
Recently I went through the Getting Started Guide again an everything worked as expected.
