### ISSUE TITLE
Update an XACML Permission

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-idm#307]
Related https://github.com/FIWARE/tutorials.Administrating-XACML/issues/7

The only way to use the API to update an XACML rule is to include dummy values as follows:

```diff
{
   "permission": {
        "action": "",
        "resource": "",
+        "use_authorization_service_header" : false, "authorization_service_header": " ",
        "xml":"..."}
}
```

The relevant logic is here in `permission.js` - there is a difference between `check_create_body_request() ` and `check_update_body_request()`

### check_update_body_request() - NOT GOOD

```javascript
if (permission.use_authorization_service_header) {
      if (typeof permission.use_authorization_service_header !== 'boolean') {
        reject(bad_request('use_authorization_service_header attribute must be a boolean'));
      }
    } else if (!permission.authorization_service_header) {
      reject(bad_request('if use_authorization_service_header is set, authorization_service_header needs to be set'));
    }
```

### check_create_body_request() - GOOD

```javascript
if (permission.use_authorization_service_header) {
      if (typeof permission.use_authorization_service_header !== 'boolean') {
        reject(bad_request('use_authorization_service_header attribute must be a boolean'));
      }
      if (!permission.authorization_service_header) {
        reject(bad_request('if use_authorization_service_header is set, authorization_service_header needs to be set'));
      }
    } else if (permission.authorization_service_header) {
      reject(bad_request('if authorization_service_header is set, use_authorization_service_header needs to be set'));
    }
```

I believe this difference is  incorrect.  `!check_create_body_request()` in [line 404](https://github.com/ging/fiware-idm/blob/master/controllers/api/permissions.js#L404) is checking for any falsy value even if `permission.use_authorization_service_header` is `false` - shouldn't the logic here align with the create function?

**Comment by apozohue10** [comment]
Hi jason,

yes, you are right. I have already fixed the issue using the same logic in check_update_body_request

BR
