### ISSUE TITLE
Authzforce via API is not working

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-idm#4]
When using the API to create roles and permissions, even though authzforce is enabled keyrock does not submit the policies to it.  I need to use the web UI to force keyrock to submit the policies (and create the domain if it doesn't exists yet).

Thanks,

Regards.

**Comment by apozohue10** [comment]
Hi, you are right, this week we will try to fix this problem.

**Comment by apozohue10** [comment]
Hi @dmabtrg,

We have implemented the functionality you told us about. Now when you create or delete a role-permission assignment through the API, the Keyrock submit new changes in policies to Authzforce.

Regards

**Comment by dmabtrg** [comment]
Hi, I've been busy with other projects and wasn't able to try it until now.  It's working.

Thanks.
