### ISSUE TITLE
Unexpected token E when authenticating Wilma with KeyRock IdM

### ISSUE THREAD

**Issue by sanchit31** [ging/fiware-idm#44]
When I make a request to Wilma PEP Proxy Server using curl command `curl -H "X-Auth-Token:afef5e33630a4e2b5fabfc61d707a4ed521ca497" http://localhost` 

Localhost is my sample App on IdM.

**My config.js on Wilma is as follows:**
var config = {};

// Used only if https is disabled
config.pep_port = 80;

// Set this var to undefined if you don't want the server to listen on HTTPS
config.https = {
    enabled: false,
    cert_file: 'cert/cert.crt',
    key_file: 'cert/key.key',
    port: 443
};

config.account_host = '172.30.66.40';

config.keystone_host = 'http://172.30.66.40';
config.keystone_port = 3000;

config.idm = {
        host: '172.30.66.34',
        port: 3000,
        ssl: false
}

config.app_host = 'www.google.com';
config.app_port = 80;
// Use true if the app server listens in https
config.app_ssl = false;

// Credentials obtained when registering PEP Proxy in Account Portal
config.app_id = '46e9c3d3-5278-4b50-8cc9-109b74429961';
config.username = 'pep_proxy_d390109f-d310-4858-98c9-8b8535b24d80';
config.password = 'pep_proxy_ad3f3197-4bcd-443c-9ef8-7529937e2059';

// in seconds
config.cache_time = 300;

// if enabled PEP checks permissions with AuthZForce GE.
// only compatible with oauth2 tokens engine
//
// you can use custom policy checks by including programatic scripts
// in policies folder. An script template is included there
config.azf = {
        enabled: false,
        protocol: 'http',
    host: '172.30.66.34',
    port: 8080,
    custom_policy: undefined // use undefined to default policy checks (HTTP verb + path).
};

// list of paths that will not check authentication/authorization
// example: ['/public/*', '/static/css/']
config.public_paths = [];

// options: oauth2/keystone
config.tokens_engine = 'oauth2';

config.magic_key = undefined;

module.exports = config;

I get the following error in logs

Checking token with IDM...
2018-10-15 11:14:36.658  - DEBUG: HTTP-Client - Sending  GET  to: http://http://172.30.66.40:3000/v3/access-tokens/afef5e33630a4e2b5fabfc61d707a4ed521ca497
2018-10-15 11:14:36.658  - DEBUG: HTTP-Client -  Headers:  { 'X-Auth-Token': undefined, Accept: 'application/json' }
2018-10-15 11:14:36.658  - DEBUG: HTTP-Client -  Body:  undefined
2018-10-15 11:14:48.673  - ERROR: Server - Caught exception: SyntaxError: Unexpected token E

When I access the same url inthe browser: [https://172.30.66.40/v3/access-tokens/afef5e33630a4e2b5fabfc61d707a4ed521ca497](https://172.30.66.40/v3/access-tokens/afef5e33630a4e2b5fabfc61d707a4ed521ca497) I get the following response: 
{"error":{"message":"Expecting to find X-Auth-token in requests","code":400,"title":"Bad Request"}}

Wilma version 5.4
IdM version 7.0

Can someone tell why is this happening?

**Comment by aalonsog** [comment]
It seems the PEP has not correctly authenticated in Keyrock because the XAuthToken header is empty.
