### ISSUE TITLE
Idm@FIWAREGlobalSummit?

### ISSUE THREAD

**Issue by fiware-austria** [ging/fiware-idm#57]
Hi @apozohue10!

Sorry for misusing github's issues. I'd just like to know whether there's anyone of you at the FIWAREGlobalSummit in Malaga?

**Comment by aalonsog** [comment]
Dear @fiware-austria, several members of FIWARE Security team will be there. We are presenting Security GEs this afternoon. Check the agenda [here](https://www.fiware.org/summit/global-2018/tuesday-nov-27th/)
