### ISSUE TITLE
How to configure email server?

### ISSUE THREAD

**Issue by emepetres** [ging/fiware-idm#7]
Admin docs are very weak about how email server should be configured to send mails for example in sign up process.
```
    config.mail = {
        host: 'idm_host',
        port: 25,
        from: 'noreply@host'
    }
```
Is the host the smtp server?
What if my smtp serve uses authentication to send mails?

**Comment by emepetres** [comment]
Doing some reverse engineering I managed to deduce that config.mail = {} follows nodemailer 'createTransport' options format (https://nodemailer.com/about/, https://nodemailer.com/smtp/).

This should be documented!

**Comment by apozohue10** [comment]
Hi @emepetres 

thanks for the suggestion. We will add how email server should be configured to the documentation.

Regards
