### ISSUE TITLE
Error 500  when creating an application

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-idm#80]
Related to https://github.com/Fiware/tutorials.Roles-Permissions/issues/6

If I attempt to create an application without a `token_type` in the payload, the application returns a  500 error (Internal Error). The error that appears in the logs is:

> TypeError: Cannot read property 'includes' of undefined

The cause is [here](https://github.com/ging/fiware-idm/blob/5531735c7aadc2a1352b6300ab1e27cc0e7ff600/controllers/api/applications.js#L168)

```javascript
 application.jwt_secret = req.body.application.token_types.includes('jwt')
```
Which assumes that `token_types` is present in the body. Since it wasn't required prior to 7.5.1 there is a high likelihood that any system that is upgrading will lack the new atribute.

There is another associated error if `token_types` is passed as an object `{}`. Line [383](https://github.com/ging/fiware-idm/blob/5531735c7aadc2a1352b6300ab1e27cc0e7ff600/controllers/api/applications.js#L383)  assumes **does** have a null check, but assumes that the entry passed must be an array without checking:

```javascript
 !body.application.token_types.every(r =>
          ['jwt', 'permanent'].includes(r)
        )
```

This also results in a 500 error

**Comment by apozohue10** [comment]
Hi @jason-fox
 
Thanks you!  We have fixed that in latest commit to master branch and also include a single test for this case.

Regards
