### ISSUE TITLE
/fiware/idm Image on dockerhub is not up to date

### ISSUE THREAD

**Issue by agaldemas** [ging/fiware-idm#81]
Hello, I have checked the date of the last image (/fiware/idm) on dockerhub is older than the last commits date, in particular the integration of postgres support is 21 days old, and the last image is one month old:
https://hub.docker.com/r/fiware/idm/tags
also it seems there's no automated build.

**Comment by apozohue10** [comment]
Hi @agaldemas 

Sorry for taking a long time to answer. Yes you were right, the docker image was not update. Currently, the latest image is updated and FIWARE_7.6 release is also available. These two docker images support posgres.

We will check the automated build ASAP.

Thanks again!

**Comment by ansh1221** [comment]
Hi @apozohue10 @agaldemas @aalonsog can I mount fiware idm on /keyrock or any path other than root.??

**Comment by agaldemas** [comment]
Hello, don't you think we can close this issue now ?

**Comment by apozohue10** [comment]
Closed!
