### ISSUE TITLE
Sign out from a service

### ISSUE THREAD

**Issue by dcalvoalonso** [ging/fiware-idm#84]
Using the Docker image: fiware/idm:7.5.1, we are trying to apply what it is explained in https://fiware-idm.readthedocs.io/en/latest/oauth/sign_out_oauth_service/index.html to log-out from our service but also from Keyrock.

Nevertheless, when we call DELETE auth/external_logout?client_id=<client_id>, we get 404 error.

**Comment by dcalvoalonso** [comment]
I see that the issue has been closed. @apozohue10 could you explain how to solve our problem?

**Comment by apozohue10** [comment]
Sorry, I

**Comment by dcalvoalonso** [comment]
We have updated to FIWARE_7.6 and now the endpoint seems to work and to redirect the log-out request to the callback defined in the user interface.

Nevertheless, KeyRock seems not to delete the session even. We have checked https://fiware-idm.readthedocs.io/en/latest/oauth/sign_out_oauth_service/ and we understand that in the latter case the user session still remains. But in our tests, in the former case (user is not logged in KeyRock yet), the session also remains.

**Comment by apozohue10** [comment]
Hi @dcalvoalonso 
Probably Keyrock doesn't find the application which is performing the sign out. An example of sign out url could be:

http://localhost:3000/auth/external_logout?_method=DELETE&client_id=1db09e5b-5574-46c9-b4ce-30f20cb70d88 

Could you tell us the url to which you are performing the sign out in Keyrock?

**Comment by dcalvoalonso** [comment]
Now it works. The problem is that I was trying to the log-out by sending a DELETE request to this url using Postman. I understand that it must be done using the same browser that it was also used to do the login, right?

**Comment by apozohue10** [comment]
Fine! Yes, you need the same browser because the user session in Keyrock is stored in cookies.
