### ISSUE TITLE
Error after update to FIWARE_7.6

### ISSUE THREAD

**Issue by dcalvoalonso** [ging/fiware-idm#86]
Following the recommendation of https://github.com/ging/fiware-idm/issues/84#issuecomment-470050088, we have updated our instance of the IDM to use the docker image with the tag FIWARE_7.6.

Now, when we try to get access to an application, we get the following error:

![Screenshot_1](https://user-images.githubusercontent.com/11388886/54212861-c121e600-44e3-11e9-97ba-8ec1a3f6010c.png)

**Comment by apozohue10** [comment]
It seems that you need to run a migration in your mysql database. In order to do that just run in your shell: npm run migrate_db.

**Comment by dcalvoalonso** [comment]
Fixed with https://github.com/ging/fiware-idm/issues/86#issuecomment-474458445. Thanks for the support! :)
