### ISSUE TITLE
Issue in integration of Fiware/idm with Fiware/apinf-platform

### ISSUE THREAD

**Issue by SourabhChourasiya-NEC** [ging/fiware-idm#87]
Hi Team,

We are working on Fiware/APInf-platform. While integrating Fiware/idm with Fiware/apinf-plaform, we're facing an internal server error on apinf sign-in.

Fiware/IDM version: 7.5.1
Apinf: 0.58.0
API Umbrella: 0.15.0-apinf2.1
Callback URl: https://<domain_name>/_oauth/fiware

- All the services running as a docker container.

We have tried it with two different scenarios:
1. Authenticate admin user
   Signing in with admin user is successful. User is redirected successfully to APInf's homepage. 
    
2. Authenticate other user who is authorized for the application
   But while signing in with any other registered user other than admin, user is not redirected to APInf's 
   homepage & it shows some Internal Server Error has occurred. As per the current scenario, if a 
   user(other than admin) tries to login to apinf via keyrock, it gets logged in into keyrock, but the error 
   occurs while redirection of it on apinf's homepage.

We have also raised the issue on [APInf](https://github.com/apinf/platform/issues/3727) community. 

Thanks

**Comment by apozohue10** [comment]
Hi @SourabhChourasiya-NEC 

I have made some authentication tests with IdM 7.5.1 and is working. As I read in APInf community it seems you need to make somo additional configurations in APInf.

Regards

**Comment by SourabhChourasiya-NEC** [comment]
Hi @apozohue10, Thank you for your inputs.
