### ISSUE TITLE
Openstack API replacement

### ISSUE THREAD

**Issue by RiosQ** [ging/fiware-idm#9]
wich is the substitute of the Openstack API for the managment of roles, users and permissions?

In the previous version for example, to generate a token for manage keystone the Request has this structure:

```bash
curl -i \
  -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "admin@test.com",
          "domain": { "id": "default" },
          "password": "1234"
        }
      }
    }
  }
}' \
  "http://localhost:3000/v3/auth/tokens" ; echo
``` 
But in this version the response is this:

```json
{
    "error": {
        "message": "Expecting to find name and password or token in body request",
        "code": 400,
        "title": "Bad Request"
    }
}
```

The funniest part is that playing with the json structure when this is the request:

```bash 
curl -i \
  -H "Content-Type: application/json" \
  -d '
{
	"name": "admin@test.com",
        "password": "1234"
}' \
  "http://localhost:3000/v3/auth/tokens" ; echo
```
this is the answer:
```json
{
    "token": {
        "methods": [
            "password"
        ],
        "expires_at": "2018-05-02T12:29:23.662Z"
    }
}
```
And presents an 401 error  in the response if the password or name is wrong, In any case the token is useless,

**Comment by RiosQ** [comment]
just is see the headers

**Comment by apozohue10** [comment]
Hi @RiosQ 

In this [link](https://keyrock.docs.apiary.io/#) you can find how to manage the API of the new IdM. The way of how tokens are generated is in the authentication section.

**Comment by joaquindiez** [comment]
ok, so you change all the API,... :-( so previous version are not going to work

**Comment by joaquindiez** [comment]
Why this documentation (https://keyrock.docs.apiary.io/#introduction/preface/acknowledgements)  is not the same that you got in http://fiware-idm.readthedocs.io/en/latest/api/???

**Comment by apozohue10** [comment]
Hi @joaquindiez 
All actions you can perform throuth the API can be found in the apiary web page. The OAuth2 Info can be found in the readthedocs web page. But you are right, we will improve the documentation of the API in both web pages.

**Comment by joaquindiez** [comment]
Hi @apozohue10 
 in previous versions, when I was creating a user I could send some extra information about the user.

But in the new versión looks like this is not working anymore, and in  the database nothing is storage

{
    "user": {
        "enabled": true,
        "admin" : false,
        "username": "XXXX",
        "email": "XXXX@VVVV.com",
        "surname": "VVVVV",
        "password": "1234",
        "config": {
          "decimals":"2",
          "lang":"en",
          "currency":"USD"
        },
        "session": {
          "loginCount":0
        }
    }
}

**Comment by RiosQ** [comment]
yes i found the documentation and is very clear, i prefer working with the API. This Issue for my is closed

**Comment by apozohue10** [comment]
Hi @joaquindiez 

By the moment this feature is not supported. We will study to add it in followings versions.

**Comment by joaquindiez** [comment]
@apozohue10 but this was a feature running in previous versions

This is a huge problem, to update to the new version form previous idm installations.

**Comment by apozohue10** [comment]
We have removed all dependency from Openstack and some of the features that were provided before are not available at the moment. But now is easier to install and manage the IdM so any suggestion as this or even to add new features are welcomed and we will try to add them in following versions.

**Comment by aalonsog** [comment]
Close due to inactivity.
